version: "3.8"
# Define services
services:
  # Service 1: Web Application
  web:
    image: python:3.9-slim
    container_name: web_app
    networks:
      - app_network
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - QUEUE_HOST=rabbitmq
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - rabbitmq
  # Service 2: PostgreSQL Database
  db:
    image: postgres:13-alpine
    container_name: postgres_db
    networks:
      - app_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Service 3: RabbitMQ (Message Queue)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - app_network
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "5672:5672"
      - "15672:15672"

# Define volumes for persistent storage
volumes:
  postgres_data:

# Define networks to allow communication between services

networks:
  app_network:
    driver: bridge
