version: "3"
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  writer:
    build: ./writer
    depends_on:
      - postgresdb
  reader:
    build: ./reader
    depends_on:
      - postgresdb
